# Generated by Django 5.1.15 on 2026-07-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimation', '0001_initial'),
        ('submissions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationweight',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_weights', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='calibrationweight',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='calibrationscheme',
            unique_together={('survey_version', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='calibrationweight',
            unique_together={('scheme', 'submission')},
        ),
    ]
