# Generated by Django 5.1.15 on 2026-07-04 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0004_version_rls_and_immutability'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('capi', 'Field interview (agent)'), ('cawi', 'Online self-response')], max_length=8)),
                ('self_selected', models.BooleanField(default=False)),
                ('answers', models.JSONField()),
                ('paradata', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('stratum', models.CharField(blank=True, max_length=128, null=True)),
                ('cluster_id', models.CharField(blank=True, max_length=128, null=True)),
                ('design_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='surveys.surveyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['survey_version', 'mode'], name='submissions_survey__57590a_idx')],
            },
        ),
    ]
