# Generated by Django 5.1.15 on 2026-07-03 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('pooled', 'Pooled (shared DB, RLS-isolated)'), ('siloed', 'Siloed (dedicated data plane)')], default='pooled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
